raw_files:
  feature_files: 
  response_files:
  boundary_files:
  feature_data_type: ['R']
  response_data_type: ['C']
  feature_nodata_value: -9999
  response_nodata_value: -9999
  boundary_bad_value: 0
  ignore_projections: True
data_build:
  dir_out:
  log_level: DEBUG
  filename_prefix_out: ''
  network_category: FCN
  random_seed: 1
  max_samples: 10000
  max_built_data_gb: 10.0
  number_folds: 10
  validation_fold: 0
  window_radius: 128
  loss_window_radius: 64
  feature_mean_centering: false
  feature_nodata_maximum_fraction: 0.25
  response_background_values: [0, 1]
data_samples:
  apply_random_transformations: true
  batch_size: 64
  feature_scaler_names: ['RobustScaler']
  response_scaler_names: ['NullScaler']
  feature_nodata_encoding: -10.0
model_training:
  dir_out: 'models/unet'
  log_level: DEBUG
  assert_gpu: true
  architecture_name: unet
  loss_metric: 'cc'
  max_epochs: 100
  optimizer: adam
  weighted: false
architecture:
  block_structure: [4, 4, 4]
  filters: 16
  kernel_size: [3, 3]
  min_conv_width: 8
  n_classes: 4
  output_activation: softmax
  padding: same
  pool_size: [2, 2]
  use_batch_norm: false
  use_growth: false
  use_initial_colorspace_transformation_layer: false
model_reporting:
  max_pages_per_figure: 1
  max_samples_per_page: 20
  max_features_per_page: 10
  max_responses_per_page: 10
  network_progression_max_pages: 1
  network_progression_max_filters: 10
  network_progression_show_full: true
  network_progression_show_compact: true
